apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app.purchaseTx.prefix }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.purchaseTx.prefix }}
  minReplicas: {{ .Values.app.purchaseTx.hpa.min }}
  maxReplicas: {{ .Values.app.purchaseTx.hpa.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.purchaseTx.hpa.cpuThreshold }}
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.purchaseTx.hpa.memoryThreshold }}