apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Namespace}}-{{ .Values.app.purchaseTx.prefix }}
  labels:
    app.service.name: {{ .Values.app.purchaseTx.prefix }}
    app.environment: {{ .Values.app.environment }}
spec:
  type: ClusterIP
  ports:
    - name: http-port
      port: {{ .Values.app.purchaseTx.port }}
      protocol: TCP
      targetPort: {{ .Values.app.purchaseTx.port }}
  selector:
    app.service.name: {{ .Values.app.purchaseTx.prefix }}
    app.environment: {{ .Values.app.environment }}
